import {product} from './product';
export const data_product:product[]=[
	{id:1,name:'Cà phê sáng tạo 8',price:250000,detail:'Từ những hạt cà phê Arabica, Robusta, Excelsa. Có hương thơm đầm, thơm rất lâu với hậu vị đậm và êm. Là một sự cân bằng hoàn hảo giữa hương và vị.',weight:250,thumbnail:'p1.jpg',images:['p1.jpg','p2.jpg','p3.jpg']},
	{id:2,name:'Bà phê sáng tạo 9',price:280000,detail:'Từ những hạt cà phê Arabica, Robusta, Excelsa. Có hương thơm đầm, thơm rất lâu với hậu vị đậm và êm. Là một sự cân bằng hoàn hảo giữa hương và vị.',weight:250,thumbnail:'p2.jpg',images:['p1.jpg','p2.jpg','p3.jpg']},
	{id:3,name:'Cà phê sáng tạo 10',price:50000,detail:'Từ những hạt cà phê Arabica, Robusta, Excelsa. Có hương thơm đầm, thơm rất lâu với hậu vị đậm và êm. Là một sự cân bằng hoàn hảo giữa hương và vị.',weight:250,thumbnail:'p3.jpg',images:['p1.jpg','p2.jpg','p3.jpg']},
	{id:4,name:'Aà phê LEGEND 1',price:25000,detail:'Từ những hạt cà phê Arabica, Robusta, Excelsa. Có hương thơm đầm, thơm rất lâu với hậu vị đậm và êm. Là một sự cân bằng hoàn hảo giữa hương và vị.',weight:250,thumbnail:'p4.jpg',images:['p1.jpg','p2.jpg','p3.jpg']},
	{id:5,name:'Dà phê LEGEND 2',price:450000,detail:'Từ những hạt cà phê Arabica, Robusta, Excelsa. Có hương thơm đầm, thơm rất lâu với hậu vị đậm và êm. Là một sự cân bằng hoàn hảo giữa hương và vị.',weight:250,thumbnail:'p1.jpg',images:['p1.jpg','p2.jpg','p3.jpg']},
	{id:6,name:'Aà phê LEGEND 3',price:150000,detail:'Từ những hạt cà phê Arabica, Robusta, Excelsa. Có hương thơm đầm, thơm rất lâu với hậu vị đậm và êm. Là một sự cân bằng hoàn hảo giữa hương và vị.',weight:250,thumbnail:'p2.jpg',images:['p1.jpg','p2.jpg','p3.jpg']},
	{id:7,name:'Là phê LEGEND 4',price:250000,detail:'Từ những hạt cà phê Arabica, Robusta, Excelsa. Có hương thơm đầm, thơm rất lâu với hậu vị đậm và êm. Là một sự cân bằng hoàn hảo giữa hương và vị.',weight:250,thumbnail:'p3.jpg',images:['p1.jpg','p2.jpg','p3.jpg']},
	{id:8,name:'Hà phê + hộp quà sáng tạo 8',price:250000,detail:'Từ những hạt cà phê Arabica, Robusta, Excelsa. Có hương thơm đầm, thơm rất lâu với hậu vị đậm và êm. Là một sự cân bằng hoàn hảo giữa hương và vị.',weight:250,thumbnail:'p4.jpg',images:['p1.jpg','p2.jpg','p3.jpg']},
	{id:9,name:'Oà phê + hộp quà sáng tạo 9',price:250000,detail:'Từ những hạt cà phê Arabica, Robusta, Excelsa. Có hương thơm đầm, thơm rất lâu với hậu vị đậm và êm. Là một sự cân bằng hoàn hảo giữa hương và vị.',weight:250,thumbnail:'p1.jpg',images:['p1.jpg','p2.jpg','p3.jpg']},
	{id:10,name:'Eà phê + hộp quà sáng tạo 10',price:250000,detail:'Từ những hạt cà phê Arabica, Robusta, Excelsa. Có hương thơm đầm, thơm rất lâu với hậu vị đậm và êm. Là một sự cân bằng hoàn hảo giữa hương và vị.',weight:250,thumbnail:'p2.jpg',images:['p1.jpg','p2.jpg','p3.jpg']},
	{id:11,name:'Fà phê + hộp quà LEGEND 6',price:250000,detail:'Từ những hạt cà phê Arabica, Robusta, Excelsa. Có hương thơm đầm, thơm rất lâu với hậu vị đậm và êm. Là một sự cân bằng hoàn hảo giữa hương và vị.',weight:250,thumbnail:'p3.jpg',images:['p1.jpg','p2.jpg','p3.jpg']},
	{id:12,name:'Và phê + hộp quà LEGEND 7',price:250000,detail:'Từ những hạt cà phê Arabica, Robusta, Excelsa. Có hương thơm đầm, thơm rất lâu với hậu vị đậm và êm. Là một sự cân bằng hoàn hảo giữa hương và vị.',weight:250,thumbnail:'p4.jpg',images:['p1.jpg','p2.jpg','p3.jpg']},
	{id:13,name:'Cà phê + hộp quà LEGEND 8',price:250000,detail:'Từ những hạt cà phê Arabica, Robusta, Excelsa. Có hương thơm đầm, thơm rất lâu với hậu vị đậm và êm. Là một sự cân bằng hoàn hảo giữa hương và vị.',weight:250,thumbnail:'p1.jpg',images:['p1.jpg','p2.jpg','p3.jpg']},
	{id:14,name:'Aà phê + hộp quà LEGEND 9',price:250000,detail:'Từ những hạt cà phê Arabica, Robusta, Excelsa. Có hương thơm đầm, thơm rất lâu với hậu vị đậm và êm. Là một sự cân bằng hoàn hảo giữa hương và vị.',weight:250,thumbnail:'p2.jpg',images:['p1.jpg','p2.jpg','p3.jpg']},
]
